.PHONY: all setup

all:
	poetry install && \
		nvm exec yarn install && \
		bundle install && bundle binstubs --force --standalone neovim

setup:
	pyenv local 3.11.6 3.11.6 && \
		poetry init --name=nvim --python=^3.11 --no-interaction && \
		poetry config --local virtualenvs.in-project true && \
		poetry add pynvim && \
		echo v20.10.0 > .nvimrc && \
		nvm use && \
		corepack enable && \
		yarn install && \
		yarn add neovim && \
		rbenv local 3.2.2 && \
		bundle init && \
		bundle add neovim
